sudo: false

language: python

matrix:
  include:
    - os: linux
      python: '2.7'
      env: CONDA=true
    - os: linux
      python: '3.6'
      env: CONDA=true
    - os: osx
      language: generic
      env: CONDA=true TRAVIS_PYTHON_VERSION=2.7
    - os: osx
      language: generic
      env: CONDA=true TRAVIS_PYTHON_VERSION=3.6

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then lsb_release -a ; fi

install:
  - PYTHON_VERSION="$TRAVIS_PYTHON_VERSION" CONDA_INSTALLER_OS="${TRAVIS_OS_NAME:-linux}" source travis_install_conda.sh numpy scipy numba;
  - conda config --set anaconda_upload no
  - conda install -n root conda-build anaconda-client
  - conda build .

# This script uses the ANACONDA_TOKEN environment variable.  To create a token do
#   > anaconda login
#   > anaconda auth -c -n travis_${PACKAGE_NAME} --max-age 307584000 --url https://anaconda.org/moble/${PACKAGE_NAME} --scopes "api:write api:read"
# then go to the Travis-CI settings page for this package, and create the environment variable with that token.
# I stole these ideas from Yoav Ram <https://gist.github.com/yoavram/05a3c04ddcf317a517d5>

after_success:
  - anaconda -t $ANACONDA_TOKEN upload --force --no-progress ${HOME}/miniconda/conda-bld/**/fftw-*.tar.bz2
