package:
  name: fftw
  version: 3.3.4

source:
  fn: fftw-3.3.4.tar.gz
  md5: 2edab8c06b24feeb3b82bbb3ebf3e7b3
  url: http://www.fftw.org/fftw-3.3.4.tar.gz

build:
  detect_binary_files_with_prefix: true

about:
  home: 'http://www.fftw.org/'
  license: GPL
  summary: "FFTW: Fastest Fourier Transform in the West"
