package:
  name: fftw
  version: 3.3.6

source:
  fn: fftw-3.3.6-pl1.tar.gz
  md5: 682a0e78d6966ca37c7446d4ab4cc2a1
  url: http://www.fftw.org/fftw-3.3.6-pl1.tar.gz

build:
  detect_binary_files_with_prefix: true

requirements:
  build:
    - python {{ python }}

about:
  home: 'http://www.fftw.org/'
  license: GPL
  summary: "FFTW: Fastest Fourier Transform in the West"
